# Generated by Django 4.1.3 on 2022-11-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Mad_City_Tickets", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Account",),
        migrations.DeleteModel(name="Venue",),
    ]
